############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1



# [[main]]
# name = "Elements"
# url = "/elements"
# weight = 3

# [[main]]
# name = "Pages"

[[main]]
weight = 2 
name = "Blog"
url = "/posts"

[[main]]
name = "About"
url = "/about"
weight = 3

# [[main]]
# parent = "Pages"
# name = "Contact"
# url = "/contact"

# [[main]]
# parent = "Pages"
# name = "Authors"
# url = "/authors"

[[main]]
name = "Categories"
url = "/categories"

# [[main]]
# parent = "Pages"
# name = "404 Page"
# url = "/404"


# footer menu
# [[footer]]
# name = "About"
# url = "/about"
# weight = 1

# [[footer]]
# name = "Elements"
# url = "/elements"
# weight = 2

# [[footer]]
# name = "Privacy Policy"
# url = "/privacy-policy"
# weight = 3
